### ISSUE TITLE
Make Verify.SyncFusion work on Linux and OSX in addition to Windows

### ISSUE THREAD

**Issue by steingran** [VerifyTests/Verify.Syncfusion#46]
#### Is the feature request related to a problem

Verify.SyncFusion currently uses the Syncfusion.EJ2.PdfViewer.AspNet.Core.Windows nuget, which is a Windows-only nuget. So when using the Verify.SyncFusion nuget on a solution that is compiled and run on Linux, this exception occurs:

System.TypeInitializationException : The type initializer for 'Syncfusion.EJ2.PdfViewer.PdfiumNative' threw an exception.
---- System.DllNotFoundException : Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/opt/atlassian/pipelines/agent/build/test/Cillco.Service.DocumentProcessing.IntegrationTests/bin/Debug/net7.0/runtimes/linux-x64/native/kernel32.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.3/kernel32.so: cannot open shared object file: No such file or directory
/opt/atlassian/pipelines/agent/build/test/Cillco.Service.DocumentProcessing.IntegrationTests/bin/Debug/net7.0/kernel32.so: cannot open shared object file: No such file or directory
/opt/atlassian/pipelines/agent/build/test/Cillco.Service.DocumentProcessing.IntegrationTests/bin/Debug/net7.0/runtimes/linux-x64/native/libkernel32.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.3/libkernel32.so: cannot open shared object file: No such file or directory
/opt/atlassian/pipelines/agent/build/test/Cillco.Service.DocumentProcessing.IntegrationTests/bin/Debug/net7.0/libkernel32.so: cannot open shared object file: No such file or directory
/opt/atlassian/pipelines/agent/build/test/Cillco.Service.DocumentProcessing.IntegrationTests/bin/Debug/net7.0/runtimes/linux-x64/native/kernel32: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.3/kernel32: cannot open shared object file: No such file or directory
/opt/atlassian/pipelines/agent/build/test/Cillco.Service.DocumentProcessing.IntegrationTests/bin/Debug/net7.0/kernel32: cannot open shared object file: No such file or directory
/opt/atlassian/pipelines/agent/build/test/Cillco.Service.DocumentProcessing.IntegrationTests/bin/Debug/net7.0/runtimes/linux-x64/native/libkernel32: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.3/libkernel32: cannot open shared object file: No such file or directory
/opt/atlassian/pipelines/agent/build/test/Cillco.Service.DocumentProcessing.IntegrationTests/bin/Debug/net7.0/libkernel32: cannot open shared object file: No such file or directory
   at Syncfusion.EJ2.PdfViewer.PdfiumNative.FPDF_InitLibrary()
   at Syncfusion.EJ2.PdfViewer.PdfiumViewer.FPDF_AddRef()
   at Syncfusion.EJ2.PdfViewer.PdfRenderer.LoadDocument(Stream fileStream, String password)
   at Syncfusion.EJ2.PdfViewer.PdfRenderer.Load(Stream fileStream)
   at VerifyTests.VerifySyncfusion.GetPdfStreams(PdfDocumentBase document, IReadOnlyDictionary`2 settings, List`1 pages)+MoveNext() in C:\projects\verify-syncfusion\src\Verify.Syncfusion\VerifySyncfusion_Pdf.cs:line 72
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VerifyTests.VerifySyncfusion.ConvertPdf(PdfLoadedDocument document, IReadOnlyDictionary`2 settings) in C:\projects\verify-syncfusion\src\Verify.Syncfusion\VerifySyncfusion_Pdf.cs:line 21
   at VerifyTests.VerifySyncfusion.ConvertPdf(Stream stream, IReadOnlyDictionary`2 settings) in C:\projects\verify-syncfusion\src\Verify.Syncfusion\VerifySyncfusion_Pdf.cs:line 9
   at VerifyTests.VerifierSettings.<>c__DisplayClass140_0.<RegisterFileConverter>b__0(Stream stream, IReadOnlyDictionary`2 context) in /_/src/Verify/Splitters/Settings_Extension.cs:line 20
   at VerifyTests.InnerVerifier.DoExtensionConversion(String extension, Stream stream, Object info) in /_/src/Verify/Verifier/InnerVerifier_Stream.cs:line 151
   at VerifyTests.InnerVerifier.VerifyStream(Stream stream, String extension, Object info) in /_/src/Verify/Verifier/InnerVerifier_Stream.cs:line 94
   at VerifyXunit.Verifier.<>c__DisplayClass7_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Xunit/Verifier.cs:line 74
--- End of stack trace from previous location ---

The above exception is from Bitbucket Pipelines, which builds and runs tests on Linux.

#### Describe the solution

The workaround I did was to add these lines to my .csproj-file:
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/22586339/233351946-a47cae6e-f4ce-4f8d-96f6-2e8ba31031ee.png">

The reason for the Conditions in the PackageReferences is that SyncFusion support staff indicates installing several of these nugets into the same project will cause problems and will not work (see https://www.syncfusion.com/forums/156778/how-to-use-pdf-viewer-with-asp-net-core-for-both-windows-and-linux-platform?reply=NtqA61). And I confirmed this, this really does not work.

There are several ways forward:
1. Include the above code in the documentation for this nuget, so people know that the nuget as-is is Windows only, but can be made to work for Linux and OSX
2. Modify the Verify.SyncFusion nuget to create three nugets: One each for Windows, Linux, and OSX (just like SyncFusion has done for the Syncfusion.EJ2.PdfViewer.AspNet.Core.* nugets)

#### Describe alternatives considered

I currently do not see any other alternatives than the two mentioned above. Which one of those to choose though, depends on the overall direction and strategy for this nuget project. 

#### Additional context

Many CI solutions are Linux-based, so making this nuget just as functional on Linux (and OSX) as on Windows would increase the attractiveness of the nuget

**Comment by SimonCropp** [comment]
happy to accept a PR for this
